

export const styles = {
    container: {
      minHeight: '100vh',
      width: '100%',
      background: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 50%, #ffffff 100%)',
      padding: '2rem',
      position: 'relative',
      overflow: 'hidden',
    },
    backgroundBlob1: {
      position: 'absolute',
      top: '5%',
      left: '5%',
      width: '300px',
      height: '300px',
      background: 'radial-gradient(circle, rgba(239, 68, 68, 0.06) 0%, transparent 70%)',
      borderRadius: '50%',
      filter: 'blur(60px)',
      animation: 'pulse 6s ease-in-out infinite',
    },
    backgroundBlob2: {
      position: 'absolute',
      top: '50%',
      right: '10%',
      width: '250px',
      height: '250px',
      background: 'radial-gradient(circle, rgba(200, 200, 200, 0.12) 0%, transparent 70%)',
      borderRadius: '50%',
      filter: 'blur(60px)',
      animation: 'pulse 6s ease-in-out infinite 3s',
    },
    backgroundBlob3: {
      position: 'absolute',
      bottom: '15%',
      left: '20%',
      width: '200px',
      height: '200px',
      background: 'radial-gradient(circle, rgba(139, 92, 246, 0.05) 0%, transparent 70%)',
      borderRadius: '50%',
      filter: 'blur(60px)',
      animation: 'pulse 6s ease-in-out infinite 4s',
    },
    floatingDots: {
      position: 'absolute',
      width: '10px',
      height: '10px',
      background: 'rgba(0, 0, 0, 0.08)',
      borderRadius: '50%',
      animation: 'float 8s ease-in-out infinite',
    },
    contentContainer: {
      position: 'relative',
      zIndex: 10,
      maxWidth: '1200px',
      margin: '0 auto',
    },
    headerCard: {
      position: 'relative',
      background: 'rgba(0, 0, 0, 0.05)',
      backdropFilter: 'blur(15px)',
      border: 'none',
      borderRadius: '24px',
      padding: '3rem 2rem',
      marginBottom: '3rem',
      boxShadow: '0 20px 40px rgba(0,0,0,0.08)',
      textAlign: 'center',
    },
    titleGlow: {
      position: 'absolute',
      top: '-15px',
      left: '-15px',
      right: '-15px',
      height: '120px',
      background: 'linear-gradient(135deg, #dc2626, #7c3aed)',
      borderRadius: '24px',
      filter: 'blur(40px)',
      opacity: 0.2,
      zIndex: -1,
    },
    title: {
      fontSize: 'clamp(2rem, 6vw, 3.5rem)',
      fontWeight: '900',
      background: 'linear-gradient(135deg, #dc2626 0%, #ec4899 50%, #a855f7 100%)',
      backgroundClip: 'text',
      WebkitBackgroundClip: 'text',
      color: 'transparent',
      margin: 0,
      lineHeight: 1.2,
    },
    historyButton: {
      position: 'absolute',
      top: '2rem',
      right: '2rem',
      background: 'linear-gradient(135deg, #dc2626, #a855f7)',
      color: 'white',
      border: 'none',
      borderRadius: '12px',
      padding: '0.75rem 1.5rem',
      fontSize: '0.9rem',
      fontWeight: '600',
      cursor: 'pointer',
      transition: 'all 0.3s ease',
      boxShadow: '0 4px 15px rgba(220, 38, 38, 0.3)',
      zIndex: 20,
    },
    drillsGrid: {
      display: 'grid',
      gridTemplateColumns: 'repeat(auto-fill, minmax(350px, 1fr))',
      gap: '2rem',
      marginTop: '2rem',
    },
    drillCard: {
      position: 'relative',
      background: 'rgba(0, 0, 0, 0.05)',
      backdropFilter: 'blur(15px)',
      border: 'none',
      borderRadius: '20px',
      padding: '2rem',
      boxShadow: '0 15px 35px rgba(0,0,0,0.08)',
      transition: 'all 0.3s ease',
      cursor: 'pointer',
      textDecoration: 'none',
      color: 'inherit',
      display: 'block',
    },
    drillCardHover: {
      transform: 'translateY(-8px) scale(1.02)',
      boxShadow: '0 25px 50px rgba(0,0,0,0.15)',
    },
    drillCardGlow: {
      position: 'absolute',
      inset: 0,
      background: 'linear-gradient(135deg, rgba(220, 38, 38, 0.1), rgba(168, 85, 247, 0.1))',
      borderRadius: '20px',
      opacity: 0,
      transition: 'opacity 0.3s ease',
      zIndex: -1,
    },
    drillTitle: {
      fontSize: '1.5rem',
      fontWeight: '700',
      color: '#1f2937',
      marginBottom: '1rem',
      lineHeight: 1.3,
    },
    drillMeta: {
      display: 'flex',
      flexDirection: 'column',
      gap: '0.75rem',
    },
    difficultyContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
    },
    difficultyLabel: {
      fontSize: '0.9rem',
      fontWeight: '600',
      color: '#6b7280',
    },
    difficultyBadge: {
      padding: '0.25rem 0.75rem',
      borderRadius: '20px',
      fontSize: '0.8rem',
      fontWeight: '600',
      textTransform: 'capitalize',
    },
    tagsContainer: {
      display: 'flex',
      alignItems: 'center',
      gap: '0.5rem',
      flexWrap: 'wrap',
    },
    tagsLabel: {
      fontSize: '0.9rem',
      fontWeight: '600',
      color: '#6b7280',
      minWidth: 'fit-content',
    },
    tag: {
      background: 'rgba(220, 38, 38, 0.1)',
      color: '#dc2626',
      padding: '0.25rem 0.5rem',
      borderRadius: '12px',
      fontSize: '0.75rem',
      fontWeight: '500',
    },
    loadingContainer: {
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 50%, #ffffff 100%)',
    },
    loadingText: {
      fontSize: '1.5rem',
      color: '#374151',
      fontWeight: '600',
    },
    errorContainer: {
      minHeight: '100vh',
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      background: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 50%, #ffffff 100%)',
    },
    errorText: {
      fontSize: '1.25rem',
      color: '#dc2626',
      fontWeight: '600',
      background: 'rgba(220, 38, 38, 0.1)',
      padding: '1rem 2rem',
      borderRadius: '12px',
    },
    emptyState: {
      textAlign: 'center',
      padding: '4rem 2rem',
      background: 'rgba(0, 0, 0, 0.03)',
      borderRadius: '20px',
      marginTop: '2rem',
    },
    emptyStateText: {
      fontSize: '1.25rem',
      color: '#6b7280',
      fontWeight: '500',
    },
  };

  export const getDifficultyStyle = (difficulty) => {
    const baseStyle = styles.difficultyBadge;
    switch (difficulty?.toLowerCase()) {
      case 'easy':
        return { ...baseStyle, background: 'rgba(34, 197, 94, 0.1)', color: '#059669' };
      case 'medium':
        return { ...baseStyle, background: 'rgba(245, 158, 11, 0.1)', color: '#d97706' };
      case 'hard':
        return { ...baseStyle, background: 'rgba(239, 68, 68, 0.1)', color: '#dc2626' };
      default:
        return { ...baseStyle, background: 'rgba(107, 114, 128, 0.1)', color: '#6b7280' };
    }
  };