export const styles = {
  container: {
    minHeight: '100vh',
    width: '100%',
    background: 'linear-gradient(135deg, #ffffff 0%, #f8fafc 50%, #ffffff 100%)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '2rem',
    position: 'relative',
    overflow: 'hidden',
  },
  backgroundBlob1: {
    position: 'absolute',
    top: '10%',
    left: '10%',
    width: '250px',
    height: '250px',
    background: 'radial-gradient(circle, rgba(239, 68, 68, 0.08) 0%, transparent 70%)',
    borderRadius: '50%',
    filter: 'blur(60px)',
    animation: 'pulse 4s ease-in-out infinite',
  },
  backgroundBlob2: {
    position: 'absolute',
    bottom: '10%',
    right: '10%',
    width: '200px',
    height: '200px',
    background: 'radial-gradient(circle, rgba(200, 200, 200, 0.15) 0%, transparent 70%)',
    borderRadius: '50%',
    filter: 'blur(60px)',
    animation: 'pulse 4s ease-in-out infinite 2s',
  },
  floatingDots: {
    position: 'absolute',
    width: '8px',
    height: '8px',
    background: 'rgba(0, 0, 0, 0.1)',
    borderRadius: '50%',
    animation: 'float 6s ease-in-out infinite',
  },
  drillCard: {
    position: 'relative',
    zIndex: 10,
    width: '100%',
    maxWidth: '800px',
    background: 'rgba(0, 0, 0, 0.05)',
    backdropFilter: 'blur(15px)',
    borderRadius: '20px',
    padding: '2.5rem',
    marginBottom: '2rem',
    boxShadow: '0 20px 40px rgba(0,0,0,0.1)',
  },
  titleGlow: {
    position: 'absolute',
    top: '-10px',
    left: '-10px',
    right: '-10px',
    height: '80px',
    background: 'linear-gradient(135deg, #dc2626, #7c3aed)',
    borderRadius: '20px',
    filter: 'blur(30px)',
    opacity: 0.3,
    zIndex: -1,
  },
  drillTitle: {
    fontSize: '2.5rem',
    marginBottom: '1rem',
    fontWeight: '900',
    background: 'linear-gradient(135deg, #dc2626 0%, #ec4899 50%, #a855f7 100%)',
    backgroundClip: 'text',
    WebkitBackgroundClip: 'text',
    color: 'transparent',
    textAlign: 'center',
  },
  difficultyText: {
    marginBottom: '2rem',
    fontSize: '1.1rem',
    color: '#374151',
    fontWeight: '600',
    textAlign: 'center',
  },
  questionCard: {
    background: 'rgba(0, 0, 0, 0.08)',
    backdropFilter: 'blur(10px)',
    borderRadius: '16px',
    padding: '1.5rem 2rem',
    marginBottom: '1.5rem',
    boxShadow: '0 8px 25px rgba(0,0,0,0.08)',
    transition: 'all 0.3s ease',
  },
  questionText: {
    fontSize: '1.3rem',
    fontWeight: '600',
    marginBottom: '1rem',
    color: '#1f2937',
    lineHeight: '1.6',
  },
  optionLabel: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '0.75rem',
    cursor: 'pointer',
    padding: '0.5rem',
    borderRadius: '8px',
    transition: 'background-color 0.2s ease',
    color: '#374151',
    fontSize: '1.1rem',
  },
  optionInput: {
    marginRight: '1rem',
    cursor: 'pointer',
    transform: 'scale(1.2)',
  },
  submitButtonContainer: {
    position: 'relative',
    display: 'flex',
    justifyContent: 'center',
    marginTop: '2rem',
  },
  submitButtonGlow: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(135deg, #dc2626, #b91c1c)',
    borderRadius: '12px',
    filter: 'blur(20px)',
    opacity: 0.8,
    zIndex: -1,
  },
  submitButton: {
    position: 'relative',
    background: 'linear-gradient(135deg, #dc2626, #b91c1c)',
    border: 'none',
    borderRadius: '12px',
    padding: '1.25rem 3rem',
    color: 'white',
    fontWeight: 'bold',
    fontSize: '1.25rem',
    cursor: 'pointer',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '0.75rem',
    boxShadow: '0 20px 40px rgba(0,0,0,0.15)',
  },
  submitButtonHover: {
    transform: 'translateY(-4px) scale(1.05)',
    background: 'linear-gradient(135deg, #b91c1c, #991b1b)',
    boxShadow: '0 25px 50px rgba(0,0,0,0.25)',
  },
  scoreCard: {
    marginTop: '2rem',
    background: 'rgba(34, 197, 94, 0.1)',
    backdropFilter: 'blur(10px)',
    borderRadius: '12px',
    padding: '1.5rem',
    textAlign: 'center',
    boxShadow: '0 10px 25px rgba(34, 197, 94, 0.1)',
  },
  scoreText: {
    fontSize: '1.5rem',
    fontWeight: '700',
    color: '#059669',
    margin: 0,
  },
  loadingContainer: {
    minHeight: '100vh',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingText: {
    fontSize: '1.5rem',
    color: '#374151',
    fontWeight: '600',
  },
};

export const getScoreStyle = (score) => {
  const base = styles.scoreText;
  if (score >= 80) return { ...base, color: '#16a34a' };
  if (score >= 60) return { ...base, color: '#f59e0b' };
  return { ...base, color: '#dc2626' };
};
